[package]
name = "dylib-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.5"
libc.workspace = true

[workspace]
resolver = "2"
members = [
  "example_lib"
]

[workspace.dependencies]
libc = "0.2.161"
