[package]
name = "dylib-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.5"
libc.workspace = true
stabby.workspace = true
shared.path = "./shared"

[profile.dev]
opt-level = 3

[workspace]
resolver = "2"
members = [
  "example_lib",
  "shared"
]

[workspace.dependencies]
libc = "0.2.161"

[workspace.dependencies.stabby]
version = "36.1.1"
features = ["libloading"]
